window.Modernizr=function(k,e,y){function s(a,b){return typeof a===b}function B(a,b){for(var d in a){var r=a[d];if(!~(""+r).indexOf("-")&&m[r]!==y)return"pfx"==b?r:!0}return!1}function q(a,b,d){var r=a.charAt(0).toUpperCase()+a.slice(1),c=(a+" "+C.join(r+" ")+r).split(" ");if(s(b,"string")||s(b,"undefined"))b=B(c,b);else{c=(a+" "+D.join(r+" ")+r).split(" ");a:{a=c;for(var e in a)if(r=b[a[e]],r!==y){b=!1===d?a[e]:s(r,"function")?r.bind(d||b):r;break a}b=!1}}return b}function N(){f.input=function(a){for(var b=
0,d=a.length;b<d;b++)E[a[b]]=a[b]in g;return E.list&&(E.list=!!e.createElement("datalist")&&!!k.HTMLDataListElement),E}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));f.inputtypes=function(a){for(var b=0,d,r,c,f=a.length;b<f;b++)g.setAttribute("type",r=a[b]),(d="text"!==g.type)&&(g.value=w,g.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(r)&&g.style.WebkitAppearance!==y?(v.appendChild(g),c=e.defaultView,d=c.getComputedStyle&&"textfield"!==
c.getComputedStyle(g,null).WebkitAppearance&&0!==g.offsetHeight,v.removeChild(g)):/^(search|tel)$/.test(r)||(/^(url|email)$/.test(r)?d=g.checkValidity&&!1===g.checkValidity():d=g.value!=w)),M[a[b]]=!!d;return M}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var f={},v=e.documentElement,c=e.createElement("modernizr"),m=c.style,g=e.createElement("input"),w=":)",x={}.toString,z=" -webkit- -moz- -o- -ms- ".split(" "),C=["Webkit","Moz","O","ms"],D=["webkit",
"moz","o","ms"],c={},M={},E={},G=[],H=G.slice,I,A=function(a,b,d,r){var c,f,g,l,t=e.createElement("div"),n=e.body,u=n||e.createElement("body");if(parseInt(d,10))for(;d--;)g=e.createElement("div"),g.id=r?r[d]:"modernizr"+(d+1),t.appendChild(g);return c=['&#173;<style id="smodernizr">',a,"</style>"].join(""),t.id="modernizr",(n?t:u).innerHTML+=c,u.appendChild(t),n||(u.style.background="",u.style.overflow="hidden",l=v.style.overflow,v.style.overflow="hidden",v.appendChild(u)),f=b(t,a),n?t.parentNode.removeChild(t):
(u.parentNode.removeChild(u),v.style.overflow=l),!!f},J=function(){var a={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(b,d){d=d||e.createElement(a[b]||"div");b="on"+b;var c=b in d;return c||(d.setAttribute||(d=e.createElement("div")),d.setAttribute&&d.removeAttribute&&(d.setAttribute(b,""),c=s(d[b],"function"),s(d[b],"undefined")||(d[b]=y),d.removeAttribute(b))),c}}(),p={}.hasOwnProperty,F;!s(p,"undefined")&&!s(p.call,"undefined")?F=
function(a,b){return p.call(a,b)}:F=function(a,b){return b in a&&s(a.constructor.prototype[b],"undefined")};Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError;var d=H.call(arguments,1),c=function(){if(this instanceof c){var e=function(){};e.prototype=b.prototype;var e=new e,f=b.apply(e,d.concat(H.call(arguments)));return Object(f)===f?f:e}return b.apply(a,d.concat(H.call(arguments)))};return c});c.flexbox=function(){return q("flexWrap")};
c.canvas=function(){var a=e.createElement("canvas");return!!a.getContext&&!!a.getContext("2d")};c.canvastext=function(){return!!f.canvas&&!!s(e.createElement("canvas").getContext("2d").fillText,"function")};c.webgl=function(){return!!k.WebGLRenderingContext};c.touch=function(){var a;return"ontouchstart"in k||k.DocumentTouch&&e instanceof DocumentTouch?a=!0:A(["@media (",z.join("touch-enabled),("),"modernizr){#modernizr{top:9px;position:absolute}}"].join(""),function(b){a=9===b.offsetTop}),a};c.geolocation=
function(){return"geolocation"in navigator};c.postmessage=function(){return!!k.postMessage};c.websqldatabase=function(){return!!k.openDatabase};c.indexedDB=function(){return!!q("indexedDB",k)};c.hashchange=function(){return J("hashchange",k)&&(e.documentMode===y||7<e.documentMode)};c.history=function(){return!!k.history&&!!history.pushState};c.draganddrop=function(){var a=e.createElement("div");return"draggable"in a||"ondragstart"in a&&"ondrop"in a};c.websockets=function(){return"WebSocket"in k||
"MozWebSocket"in k};c.rgba=function(){m.cssText="background-color:rgba(150,255,150,.5)";return!!~(""+m.backgroundColor).indexOf("rgba")};c.hsla=function(){m.cssText="background-color:hsla(120,40%,100%,.5)";return!!~(""+m.backgroundColor).indexOf("rgba")||!!~(""+m.backgroundColor).indexOf("hsla")};c.multiplebgs=function(){m.cssText="background:url(https://),url(https://),red url(https://)";return/(url\s*\(.*?){3}/.test(m.background)};c.backgroundsize=function(){return q("backgroundSize")};c.borderimage=
function(){return q("borderImage")};c.borderradius=function(){return q("borderRadius")};c.boxshadow=function(){return q("boxShadow")};c.textshadow=function(){return""===e.createElement("div").style.textShadow};c.opacity=function(){var a=z.join("opacity:.55;")+"";m.cssText=a;return/^0.55$/.test(m.opacity)};c.cssanimations=function(){return q("animationName")};c.csscolumns=function(){return q("columnCount")};c.cssgradients=function(){var a=("background-image:-webkit-gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:"+
z.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);m.cssText=a;return!!~(""+m.backgroundImage).indexOf("gradient")};c.cssreflections=function(){return q("boxReflect")};c.csstransforms=function(){return!!q("transform")};c.csstransforms3d=function(){var a=!!q("perspective");return a&&"webkitPerspective"in v.style&&A("@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px;}}",function(b,d){a=9===b.offsetLeft&&3===b.offsetHeight}),a};
c.csstransitions=function(){return q("transition")};c.fontface=function(){var a;return A('@font-face {font-family:"font";src:url("https://")}',function(b,d){var c=e.getElementById("smodernizr"),c=(c=c.sheet||c.styleSheet)?c.cssRules&&c.cssRules[0]?c.cssRules[0].cssText:c.cssText||"":"";a=/src/i.test(c)&&0===c.indexOf(d.split(" ")[0])}),a};c.generatedcontent=function(){var a;return A(['#modernizr{font:0/0 a}#modernizr:after{content:"',w,'";visibility:hidden;font:3px/1 a}'].join(""),function(b){a=3<=
b.offsetHeight}),a};c.video=function(){var a=e.createElement("video"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,""),b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,"")}catch(d){}return b};c.audio=function(){var a=e.createElement("audio"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,
""),b.mp3=a.canPlayType("audio/mpeg;").replace(/^no$/,""),b.wav=a.canPlayType('audio/wav; codecs="1"').replace(/^no$/,""),b.m4a=(a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")).replace(/^no$/,"")}catch(d){}return b};c.localstorage=function(){try{return localStorage.setItem("modernizr","modernizr"),localStorage.removeItem("modernizr"),!0}catch(a){return!1}};c.sessionstorage=function(){try{return sessionStorage.setItem("modernizr","modernizr"),sessionStorage.removeItem("modernizr"),!0}catch(a){return!1}};
c.webworkers=function(){return!!k.Worker};c.applicationcache=function(){return!!k.applicationCache};c.svg=function(){return!!e.createElementNS&&!!e.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect};c.inlinesvg=function(){var a=e.createElement("div");return a.innerHTML="<svg/>","http://www.w3.org/2000/svg"==(a.firstChild&&a.firstChild.namespaceURI)};c.smil=function(){return!!e.createElementNS&&/SVGAnimate/.test(x.call(e.createElementNS("http://www.w3.org/2000/svg","animate")))};c.svgclippaths=
function(){return!!e.createElementNS&&/SVGClipPath/.test(x.call(e.createElementNS("http://www.w3.org/2000/svg","clipPath")))};for(var K in c)F(c,K)&&(I=K.toLowerCase(),f[I]=c[K](),G.push((f[I]?"":"no-")+I));f.input||N();f.addTest=function(a,b){if("object"==typeof a)for(var d in a)F(a,d)&&f.addTest(d,a[d]);else{a=a.toLowerCase();if(f[a]!==y)return f;b="function"==typeof b?b():b;v.className+=" "+(b?"":"no-")+a;f[a]=b}return f};m.cssText="";return c=g=null,function(a,b){function d(){var b=m.elements;
return"string"==typeof b?b.split(" "):b}function c(b){var a=h[b[k]];return a||(a={},q++,b[k]=q,h[q]=a),a}function e(a,d,f){d||(d=b);if(L)return d.createElement(a);f||(f=c(d));var h;return f.cache[a]?h=f.cache[a].cloneNode():n.test(a)?h=(f.cache[a]=f.createElem(a)).cloneNode():h=f.createElem(a),h.canHaveChildren&&!t.test(a)&&!h.tagUrn?f.frag.appendChild(h):h}function f(b,a){a.cache||(a.cache={},a.createElem=b.createElement,a.createFrag=b.createDocumentFragment,a.frag=a.createFrag());b.createElement=
function(d){return m.shivMethods?e(d,b,a):a.createElem(d)};b.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+d().join().replace(/[\w\-]+/g,function(b){return a.createElem(b),a.frag.createElement(b),'c("'+b+'")'})+");return n}")(m,a.frag)}function g(a){a||(a=b);var d=c(a);if(m.shivCSS&&!u&&!d.hasCSS){var e,h=a;e=h.createElement("p");h=h.getElementsByTagName("head")[0]||h.documentElement;e=(e.innerHTML="x<style>article,aside,dialog,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}mark{background:#FF0;color:#000}template{display:none}</style>",
h.insertBefore(e.lastChild,h.firstChild));d.hasCSS=!!e}return L||f(a,d),a}var l=a.html5||{},t=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,n=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,u,k="_html5shiv",q=0,h={},L;(function(){try{var a=b.createElement("a");a.innerHTML="<xyz></xyz>";u="hidden"in a;var d;if(!(d=1==a.childNodes.length)){b.createElement("a");var c=b.createDocumentFragment();d="undefined"==typeof c.cloneNode||
"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}L=d}catch(e){L=u=!0}})();var m={elements:l.elements||"abbr article aside audio bdi canvas data datalist details dialog figcaption figure footer header hgroup main mark meter nav output progress section summary template time video",version:"3.7.0",shivCSS:!1!==l.shivCSS,supportsUnknownElements:L,shivMethods:!1!==l.shivMethods,type:"default",shivDocument:g,createElement:e,createDocumentFragment:function(a,e){a||(a=b);
if(L)return a.createDocumentFragment();e=e||c(a);for(var h=e.frag.cloneNode(),f=0,n=d(),t=n.length;f<t;f++)h.createElement(n[f]);return h}};a.html5=m;g(b)}(this,e),f._version="2.8.3",f._prefixes=z,f._domPrefixes=D,f._cssomPrefixes=C,f.hasEvent=J,f.testProp=function(a){return B([a])},f.testAllProps=q,f.testStyles=A,f.prefixed=function(a,b,d){return b?q(a,b,d):q(a,"pfx")},v.className=v.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+G.join(" ")),f}(this,this.document);
(function(k,e,y){function s(b){return"[object Function]"==z.call(b)}function B(b){return"string"==typeof b}function q(){}function N(b){return!b||"loaded"==b||"complete"==b||"uninitialized"==b}function f(){var b=C.shift();D=1;b?b.t?w(function(){("c"==b.t?a.injectCss:a.injectJs)(b.s,0,b.a,b.x,b.e,1)},0):(b(),f()):D=0}function v(b,d,c,g,k,q,l){function t(a){if(!u&&N(n.readyState)&&(s.r=u=1,!D&&f(),n.onload=n.onreadystatechange=null,a)){"img"!=b&&w(function(){G.removeChild(n)},50);for(var c in p[d])p[d].hasOwnProperty(c)&&
p[d][c].onload()}}l=l||a.errorTimeout;var n=e.createElement(b),u=0,m=0,s={t:c,s:d,e:k,a:q,x:l};1===p[d]&&(m=1,p[d]=[]);"object"==b?n.data=d:(n.src=d,n.type=b);n.width=n.height="0";n.onerror=n.onload=n.onreadystatechange=function(){t.call(this,m)};C.splice(g,0,s);"img"!=b&&(m||2===p[d]?(G.insertBefore(n,E?null:x),w(t,l)):p[d].push(n))}function c(b,a,c,e,g){return D=0,a=a||"j",B(b)?v("c"==a?I:H,b,a,this.i++,c,e,g):(C.splice(this.i++,0,b),1==C.length&&f()),this}function m(){var b=a;return b.loader={load:c,
i:0},b}var g=e.documentElement,w=k.setTimeout,x=e.getElementsByTagName("script")[0],z={}.toString,C=[],D=0,M="MozAppearance"in g.style,E=M&&!!e.createRange().compareNode,G=E?g:x.parentNode,g=k.opera&&"[object Opera]"==z.call(k.opera),g=!!e.attachEvent&&!g,H=M?"object":g?"script":"img",I=g?"script":H,A=Array.isArray||function(b){return"[object Array]"==z.call(b)},J=[],p={},F={timeout:function(b,a){return a.length&&(b.timeout=a[0]),b}},K,a;a=function(b){function c(b){b=b.split("!");var a=J.length,d=
b.pop(),e=b.length,d={url:d,origUrl:d,prefixes:b},f,h,g;for(h=0;h<e;h++)g=b[h].split("="),(f=F[g.shift()])&&(d=f(d,g));for(h=0;h<a;h++)d=J[h](d);return d}function e(b,a,f,g,k){var h=c(b),l=h.autoCallback;h.url.split(".").pop().split("?").shift();h.bypass||(a&&(a=s(a)?a:a[b]||a[g]||a[b.split("/").pop().split("?")[0]]),h.instead?h.instead(b,a,f,g,k):(p[h.url]?h.noexec=!0:p[h.url]=1,f.load(h.url,h.forceCSS||!h.forceJS&&"css"==h.url.split(".").pop().split("?").shift()?"c":y,h.noexec,h.attrs,h.timeout),
(s(a)||s(l))&&f.load(function(){m();a&&a(h.origUrl,k,g);l&&l(h.origUrl,k,g);p[h.url]=2})))}function f(a,b){function c(a,f){if(a)if(B(a))f||(h=function(){var a=[].slice.call(arguments);k.apply(this,a);l()}),e(a,h,b,0,d);else{if(Object(a)===a)for(p in m=function(){var b=0,d;for(d in a)a.hasOwnProperty(d)&&b++;return b}(),a)a.hasOwnProperty(p)&&(!f&&!--m&&(s(h)?h=function(){var a=[].slice.call(arguments);k.apply(this,a);l()}:h[p]=function(a){return function(){var b=[].slice.call(arguments);a&&a.apply(this,
b);l()}}(k[p])),e(a[p],h,b,p,d))}else!f&&l()}var d=!!a.test,g=a.load||a.both,h=a.callback||q,k=h,l=a.complete||q,m,p;c(d?a.yep:a.nope,!!g);g&&c(g)}var g,k,l=this.yepnope.loader;if(B(b))e(b,0,l,0);else if(A(b))for(g=0;g<b.length;g++)k=b[g],B(k)?e(k,0,l,0):A(k)?a(k):Object(k)===k&&f(k,l);else Object(b)===b&&f(b,l)};a.addPrefix=function(a,d){F[a]=d};a.addFilter=function(a){J.push(a)};a.errorTimeout=1E4;null==e.readyState&&e.addEventListener&&(e.readyState="loading",e.addEventListener("DOMContentLoaded",
K=function(){e.removeEventListener("DOMContentLoaded",K,0);e.readyState="complete"},0));k.yepnope=m();k.yepnope.executeStack=f;k.yepnope.injectJs=function(b,d,c,g,k,m){var l=e.createElement("script"),p,n;g=g||a.errorTimeout;l.src=b;for(n in c)l.setAttribute(n,c[n]);d=m?f:d||q;l.onreadystatechange=l.onload=function(){!p&&N(l.readyState)&&(p=1,d(),l.onload=l.onreadystatechange=null)};w(function(){p||(p=1,d(1))},g);k?l.onload():x.parentNode.insertBefore(l,x)};k.yepnope.injectCss=function(a,c,g,k,m,p){k=
e.createElement("link");var l;c=p?f:c||q;k.href=a;k.rel="stylesheet";k.type="text/css";for(l in g)k.setAttribute(l,g[l]);m||(x.parentNode.insertBefore(k,x),w(c,0))}})(this,document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};
