function createEl(c){var a=document.createElement("div");a.innerHTML=c.trim();return a.firstChild}function createSvgEl(c){return createEl('\n    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">'+c.trim()+"</svg>\n  ")}function createSvgChildEl(c){return createSvgEl(c).firstChild}function createLine(c){return createSvgChildEl('\n    <rect x="'+c.x+'" y="'+c.y+'" width="'+c.width+'" height="'+c.height+'" fill="'+c.color+'">\n  ')}
var pageEl=document.querySelector("#page"),introEl=document.querySelector("#intro"),stripesEl=document.querySelector("#stripes"),logoContainer=document.querySelector("#logo-container"),logo=logoContainer.querySelector("svg"),logoPath=logo.querySelector("path"),windowWidth=document.body.clientWidth,windowHeight=document.body.clientHeight;
function _animateStripes(c){var a=1>=arguments.length||void 0===arguments[1]?{}:arguments[1];a.count=a.count||10;a.sizeRatio=a.sizeRatio||1;for(var f=[],d=function(b){var d=void 0,d=a.color?a.color:tinycolor("hsl("+Math.round(360*Math.random())+", 80%, 65%)").toRgbString(),g=Math.max(windowWidth,1E3),g=Math.round(g/10+Math.random()*g/10)*a.sizeRatio,m=Math.round(10*Math.random()+2)*a.sizeRatio,p=void 0,p=a.point?{x:Math.round(a.point.x-g/2+200*Math.random()-100),y:Math.round(a.point.y-m/2+50*Math.random()-
25)}:{x:Math.round((windowWidth+g)*Math.random()-g),y:Math.round(windowHeight*Math.random())},k={x:p.x,y:p.y,width:g,height:m,color:d},l=createLine(k);l.style.display="none";c.appendChild(l);dynamics.setTimeout(function(){l.style.display="block";dynamics.setTimeout(function(){k.x+=100*Math.random()-50;k.y+=20*Math.random()-10;l.setAttribute("x",k.x);l.setAttribute("y",k.y);var d=a.transform({width:k.width,height:k.height});l.setAttribute("width",d.width);l.setAttribute("height",d.height);dynamics.setTimeout(function(){c.removeChild(l)},
a.delay("hide",b))},a.delay("transform",b))},a.delay("show",b));f.push(l)},b=0;b<a.count;b++)d(b);return f}function animateBlackStripes(c){var a=1>=arguments.length||void 0===arguments[1]?{}:arguments[1];a.sizeRatio=3;a.color="#101214";a.delay=function(c,d){if("show"===c)return a.delayShow?50*Math.random():0;if("transform"===c)return 20*Math.random()+2*d;if("hide"===c)return 100};a.transform=function(a){return{width:a.width/2,height:a.height/5}};_animateStripes(c,a)}
function animateColoredStripes(c){var a=1>=arguments.length||void 0===arguments[1]?{}:arguments[1];a.delay=function(a,c){if("show"===a)return 300*Math.random();if("transform"===a)return 20*Math.random();if("hide"===a)return 100};a.transform=function(a){return{width:a.width/2,height:a.height/5}};_animateStripes(c,a)}var totalMaskIdx=0;
function createMasksWithStripes(c,a){for(var f=2>=arguments.length||void 0===arguments[2]?10:arguments[2],d=[],b=0;b<c;b++)d.push([]);for(var e=[],b=totalMaskIdx;b<totalMaskIdx+d.length;b++)e.push("clipPath"+b);totalMaskIdx+=d.length;for(var h=b=0,g=0,m=f;;){var p=Math.max(10*m,Math.round(Math.random()*a.width));d[b].push("\n      M "+h+","+g+" L "+(h+p)+","+g+" L "+(h+p)+","+(g+m)+" L "+h+","+(g+m)+" Z\n    ");b+=1;b>=d.length&&(b=0);h+=p;h>a.width&&(h=0,g+=m,m=Math.round(Math.random()*f+f/2));if(g>=
a.height)break}d.forEach(function(a,b){var c=createSvgChildEl('<clipPath id="'+e[b]+'">\n      <path d="'+a.join(" ")+'" fill="white"></path>\n    </clipPath>');document.querySelector("#clip-paths g").appendChild(c)});return e}
function cloneAndStripeElement(c,a,f){var d=c.cloneNode(!0),b=c.getBoundingClientRect(),e=f.getBoundingClientRect(),b={top:b.top-e.top,left:b.left-e.left,width:b.width,height:b.height};c=window.getComputedStyle(c);dynamics.css(d,{position:"absolute",left:Math.round(b.left+window.scrollX),top:Math.round(b.top+window.scrollY),width:Math.ceil(b.width),height:Math.ceil(b.height),display:"none",pointerEvents:"none",background:"#101214",fontSize:c.fontSize,fontFamily:c.fontFamily,color:c.color,textDecoration:c.textDecoration});
f.appendChild(d);d.style["-webkit-clip-path"]="url(/#"+a+")";d.style["clip-path"]="url(/#"+a+")";return d}var contentEls=[],originalContentEls=document.querySelectorAll("#header-content, #content");
(function(){var c=originalContentEls;pageEl.getBoundingClientRect();for(var a=0;a<c.length;a++){for(var f=c[a],d=f.getBoundingClientRect(),d=createMasksWithStripes(6,d),b=0;b<d.length;b++){var e=cloneAndStripeElement(f,d[b],pageEl);e.setAttribute("data-idx",b);contentEls.push(e);for(var e=e.querySelectorAll("h2, ul > li > a, a.more, h1, p, path"),h=0;h<e.length;h++){var g=tinycolor("hsl("+Math.round(360*Math.random())+", 80%, 65%)").toRgbString();dynamics.css(e[h],{color:g,fill:g})}}f.style.visibility=
"hidden"}})();
function showContent(){for(var c=0,a=function(a){var b=contentEls[a];a=50+Math.round(350*Math.random());var e={translateX:Math.round(40*Math.random()-20)},h=3>=b.getAttribute("data-idx");dynamics.css(b,e);dynamics.setTimeout(function(){dynamics.css(b,{display:""})},a);c=Math.max(c,a);dynamics.setTimeout(function(){dynamics.css(b,{translateX:Math.round(e.translateX/-5)})},a+100);dynamics.setTimeout(function(){dynamics.css(b,{translateX:0,translateY:0});h||b.parentNode.removeChild(b)},a+150);h&&(dynamics.setTimeout(function(){dynamics.css(b,
{translateX:Math.round(e.translateX/-2)})},a+300),dynamics.setTimeout(function(){b.parentNode.removeChild(b)},a+550))},f=0;f<contentEls.length;f++)a(f);dynamics.setTimeout(function(){for(var a=0;a<originalContentEls.length;a++)originalContentEls[a].style.visibility="visible"},c)}
(function(){function c(){dynamics.css(logoContainer,{scale:0.5,translateX:100*Math.random()-50});dynamics.setTimeout(function(){dynamics.css(logoContainer,{translateX:10,scale:0.55})},100);dynamics.setTimeout(function(){dynamics.css(logoContainer,{translateX:0,scale:0.5})},150)}animateBlackStripes(stripesEl,{count:200});animateColoredStripes(stripesEl,{count:100});dynamics.css(pageEl,{scale:0.95});dynamics.animate(pageEl,{scale:1},{type:dynamics.easeInOut,friction:500,duration:4E3});dynamics.css(logo,
{scale:1});dynamics.animate(logo,{scale:0.9},{duration:1500,type:dynamics.easeOut});var a=tinycolor("hsl("+Math.round(360*Math.random())+", 80%, 65%)");dynamics.animate(logoPath,{fill:a.toRgbString()},{duration:700});a=tinycolor("hsl("+Math.round(360*Math.random())+", 80%, 65%)");dynamics.animate(logoPath,{fill:a.toRgbString()},{duration:700,delay:700});c();dynamics.setTimeout(function(){logoContainer.style.visibility="visible"},1);dynamics.setTimeout(function(){c();animateBlackStripes(stripesEl,
{count:200,delayShow:!0});animateColoredStripes(stripesEl,{count:100})},1E3);dynamics.setTimeout(function(){introEl.style.backgroundColor="transparent";dynamics.css(logoContainer,{scale:1,translateX:Math.random()*windowWidth-windowWidth/2,translateY:Math.random()*windowHeight-windowHeight/2});showContent()},1300);dynamics.setTimeout(function(){dynamics.css(logoContainer,{scale:0.75})},1350);dynamics.setTimeout(function(){logo.style.display="none"},1400);dynamics.setTimeout(function(){document.body.removeChild(introEl)},
3E3)})();
(function(){function c(){for(var a=document.querySelector("#header-logo"),b=a.getBoundingClientRect(),c=10+10*Math.random(),b=createMasksWithStripes(c,b,Math.round(100/c)),d=[],c=0;c<b.length;c++){var e=cloneAndStripeElement(a,b[c],document.body),f=e.querySelector("path"),t=tinycolor("hsl("+Math.round(360*Math.random())+", 80%, 65%)");dynamics.css(f,{fill:t.toRgbString()});d.push(e)}a=function(a){var b=d[a];a=100*Math.random();dynamics.setTimeout(function(){b.style.display="";dynamics.css(b,{translateX:100*
Math.random()-50})},a);dynamics.setTimeout(function(){dynamics.css(b,{translateX:20*Math.random()-10})},a+50);dynamics.setTimeout(function(){dynamics.css(b,{translateX:5*Math.random()-2.5})},a+100);dynamics.setTimeout(function(){document.body.removeChild(b)},a+150)};for(b=0;b<d.length;b++)a(b)}function a(){dynamics.setTimeout(function(){c();a()},100+5E3*Math.random())}function f(a){for(var b=a.target;b&&"a"!==b.tagName.toLowerCase();)b=b.parentNode;if(b){var c=d(b);b.addEventListener("mouseout",function k(a){b.removeEventListener("mouseout",
k);c.stop()})}}function d(a){var b=!0,c=a.getBoundingClientRect();(function k(){for(var d=createMasksWithStripes(3,c,3),e=[],f=0;f<d.length;f++){var n=cloneAndStripeElement(a,d[f],document.body),q=Array.prototype.slice.apply(n.querySelectorAll("path"));q.push(n);for(var r=0;r<q.length;r++){var s=tinycolor("hsl("+Math.round(360*Math.random())+", 80%, 65%)").toRgbString();dynamics.css(q[r],{color:s,fill:s})}n.style.display="";e.push(n)}f=function(a){var b=e[a];dynamics.css(b,{translateX:10*Math.random()-
5});dynamics.setTimeout(function(){dynamics.css(b,{translateX:0})},50);dynamics.setTimeout(function(){dynamics.css(b,{translateX:5*Math.random()-2.5})},100);dynamics.setTimeout(function(){document.body.removeChild(b)},150)};for(n=0;n<e.length;n++)f(n);dynamics.setTimeout(function(){b&&k();for(var a=0;a<d.length;a++){var c=document.querySelector("#"+d[a]);c.parentNode.removeChild(c)}},1E3*Math.random())})();return{stop:function(){b=!1}}}document.querySelector("#page-stripes");var b=document.querySelectorAll("a");
dynamics.setTimeout(a,4E3);document.querySelector("#header-logo").addEventListener("mouseover",c);if(!("ontouchstart"in window))for(var e=0;e<b.length;e++)b[e].addEventListener("mouseover",f)})();
